apiVersion: v1
kind: ConfigMap
metadata:
    name: book-api-configmap
data:
    PORT: "5000"
    MYSQL_DB_NAME: "mydb"
    MYSQL_USERNAME: "root"
    MYSQL_PASSWORD: "password"
    MYSQL_HOST: "mysql-service"
    JWT_EXPIRY: "2629800000"
    JWT_SECRET: "secret"
    COOKIE_SECRET: "secret"
    AUTH_COOKIE_NAME: "access-token"
