apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql-db
    template:
        metadata:
            labels:
                app: mysql-db
        spec:
            containers:
                - name: mysql-db-container
                  image: mysql:latest
                  env:
                    - name: MYSQL_ROOT_PASSWORD
                      value: samurai
                    - name: MYSQL_DATABASE
                      value: code_samurai_2024
                  ports:
                      - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
    name: mysql-service
spec:
    ports:
        - name: tcp
          port: 3306
          targetPort: 3306
    selector:
        app: mysql-db
