version: "3"

services:
    app-server:
        build: .
        ports:
            - "5000:5000"
        environment:
            - PORT=5000
            - MYSQL_DB_NAME=code_samurai_2024
            - MYSQL_USERNAME=root
            - MYSQL_PASSWORD=samurai
            - MYSQL_HOST=database-server
            - JWT_EXPIRY=2629800000
            - JWT_SECRET=code
            - COOKIE_SECRET=code
            - AUTH_COOKIE_NAME=name
        depends_on:
            - database-server
        # volumes:
        #     - .:/app

    database-server:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: samurai
            MYSQL_DATABASE: code_samurai_2024
        volumes:
            - optimists-db-store:/var/lib/mysql

volumes:
    optimists-db-store:
