version: '3'
services:
  nodejs-app:
    image: first-app-back-end
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - minio
    networks:
      - first_app_network

  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - first_app_network

  minio:
    image: minio/minio
    ports:
      - "9005:9000"
      - "9006:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    networks:
      - first_app_network


volumes:
  mongo-data:
  minio-data:


networks:
  first_app_network:
    driver: bridge
